name: Image Builds
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04-arm # arm64!!!
    strategy:
      fail-fast: false
      matrix:
        include:
          - image-name: ghcr.io/${{ github.repository }}:latest
            context: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Buildx automates creating the multi-arch manifest build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Finally, build and push the images
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          platforms: linux/arm64
          build-args: |
            REVISION=${{ github.sha }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.image-name }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow}}
